# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch
import torchvision
import numpy

# Create random tensor
t1 = torch.rand(7,7)
t1, t1.shape


(tensor([[0.2694, 0.3351, 0.0842, 0.7134, 0.3325, 0.4709, 0.6057],
         [0.0228, 0.4883, 0.4003, 0.6140, 0.7531, 0.6110, 0.5489],
         [0.4348, 0.9745, 0.3581, 0.3138, 0.3838, 0.8670, 0.8140],
         [0.4628, 0.3804, 0.4242, 0.6970, 0.8810, 0.6408, 0.0350],
         [0.7759, 0.5616, 0.3012, 0.5858, 0.6315, 0.2182, 0.3594],
         [0.3537, 0.7237, 0.2797, 0.6627, 0.5255, 0.2959, 0.1634],
         [0.4727, 0.3181, 0.4584, 0.0767, 0.0583, 0.0814, 0.8185]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
t2 = torch.rand(1,7)
# Perform matrix multiplication 
t3 = torch.mm(t1,t2.T)
t3, t3.shape

(tensor([[1.3516],
         [1.7197],
         [2.0276],
         [1.4299],
         [1.3880],
         [1.1719],
         [1.4455]]),
 torch.Size([7, 1]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [5]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
t1 = torch.rand(7,7)
t2 = torch.rand(1,7)


# Matrix multiply tensors
t3 = torch.mm(t1,t2.T)
t3, t3.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [6]:
# Set random seed on the GPU
device = "mps" if torch.backends.mps.is_available() else "cpu"
device

'mps'


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [13]:
# Set random seed
# torch.mps.manual_seed(1234)
# Check for access to GPU
torch.manual_seed(1234)
# Create two random tensors on GPU
rt1 = torch.rand(2,3)
rt2 = torch.rand(2,3)
rt1_gpu = rt1.to(device)
rt2_gpu = rt2.to(device)
print(rt1_gpu)
print(rt2_gpu)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='mps:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='mps:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B
ct3_gpu = torch.mm(rt1_gpu,rt2_gpu.T)
print(ct3_gpu)


tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='mps:0')
mps:0


### 8. Find the maximum and minimum values of the output of 7.

In [16]:
# Find max
print(f"Max: {ct3_gpu.max()}")
# Find min
print(f"Min: {ct3_gpu.min()}")


Max: 0.5617256760597229
Min: 0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [17]:
# Find arg max
print(f"Arg Max: {ct3_gpu.argmax()}")

# Find arg min
print(f"Arg Min: {ct3_gpu.argmin()}")


Arg Max: 3
Arg Min: 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [23]:
# Set seed
torch.manual_seed(7)

# Create random tensor
rand1 = torch.rand(1,1,1,10)

# Remove single dimensions
new_tensor = torch.squeeze(rand1)

# Print out tensors and their shapes
print(f"Tensor OG: {rand1}\nOG Shape: {rand1.shape}\n")
print(f"New Tensor: {new_tensor}\nNew Shape: {new_tensor.shape}")

Tensor OG: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
OG Shape: torch.Size([1, 1, 1, 10])

New Tensor: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
New Shape: torch.Size([10])
