In [ ]:
import torch 
import torchvision
import numpy as np

'0.26.0'

In [13]:
# tensors 
data =[[1,2],[3,4]]
x_data = torch.tensor(data)
scalar = 7
t_scale = torch.tensor(scalar)
print(x_data,t_scale)
print(x_data.ndim)

# using np array
np_arr = np.array(data)
x_np = torch.from_numpy(np_arr)
print(x_np)

# from another tensor args (shape, dtype)
x_same = torch.ones_like(x_data)

x_rand = torch.rand_like(x_data,dtype=torch.float)
print(x_rand)


tensor([[1, 2],
        [3, 4]]) tensor(7)
2
tensor([[1, 2],
        [3, 4]])
tensor([[0.6004, 0.1552],
        [0.2022, 0.9659]])


In [14]:
# shape is a tuple of tensor dimensions
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.7287, 0.8152, 0.9155],
        [0.4615, 0.0498, 0.7791]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [15]:
# Has attributes shape, dtype and device it is stored on
tensor = torch.rand((2,3,2))
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([2, 3, 2])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [ ]:
# Operations