In [65]:
import torch 
import torchvision
import numpy as np

In [66]:
# tensors 
data =[[1,2],[3,4]]
x_data = torch.tensor(data)
scalar = 7
t_scale = torch.tensor(scalar)
print(x_data,t_scale)
print(x_data.ndim)

# using np array
np_arr = np.array(data)
x_np = torch.from_numpy(np_arr)
print(x_np)

# from another tensor args (shape, dtype)
x_same = torch.ones_like(x_data)

x_rand = torch.rand_like(x_data,dtype=torch.float)
print(x_rand)


tensor([[1, 2],
        [3, 4]]) tensor(7)
2
tensor([[1, 2],
        [3, 4]])
tensor([[0.2093, 0.2544],
        [0.6957, 0.7599]])


In [67]:
# shape is a tuple of tensor dimensions
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.5817, 0.3251, 0.0765],
        [0.5001, 0.0054, 0.8203]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [68]:
# Has attributes shape, dtype and device it is stored on
tensor = torch.rand((2,3,2))
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([2, 3, 2])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [69]:
# Operations
torch.backends.mps.is_available()
if torch.accelerator.is_available():
    tensor=tensor.to(torch.accelerator.current_accelerator())
    


In [70]:
# NumPy like indexing/slicing
tensor = torch.tensor([[1,3,5],[1,5,6],[0,9,4],[31,3,5]])
print(f"First Row: {tensor[0]}")
print(f"First Column: {tensor[:,0]}")
print(f"Last Column: {tensor[:,-1]}")

First Row: tensor([1, 3, 5])
First Column: tensor([ 1,  1,  0, 31])
Last Column: tensor([5, 6, 4, 5])


In [71]:
tensor[:,1]=0 #make the 2nd column zeros 
tensor

tensor([[ 1,  0,  5],
        [ 1,  0,  6],
        [ 0,  0,  4],
        [31,  0,  5]])

In [72]:
# torch.cat to join tensors (extends along one dimension)
t1 = torch.cat([tensor,tensor,tensor],dim=0)
print(t1)
# can also use torch.stack (creates a new dimension (2d->3d or 3d->4d))
torch.stack([tensor,tensor,tensor],dim=0)

tensor([[ 1,  0,  5],
        [ 1,  0,  6],
        [ 0,  0,  4],
        [31,  0,  5],
        [ 1,  0,  5],
        [ 1,  0,  6],
        [ 0,  0,  4],
        [31,  0,  5],
        [ 1,  0,  5],
        [ 1,  0,  6],
        [ 0,  0,  4],
        [31,  0,  5]])


tensor([[[ 1,  0,  5],
         [ 1,  0,  6],
         [ 0,  0,  4],
         [31,  0,  5]],

        [[ 1,  0,  5],
         [ 1,  0,  6],
         [ 0,  0,  4],
         [31,  0,  5]],

        [[ 1,  0,  5],
         [ 1,  0,  6],
         [ 0,  0,  4],
         [31,  0,  5]]])

In [73]:
y1 = t1 @ t1.T
print(y1)
y2 = tensor.matmul(tensor.T)
print(y2)

z1= tensor * tensor
z1.add_(5)

tensor([[ 26,  31,  20,  56,  26,  31,  20,  56,  26,  31,  20,  56],
        [ 31,  37,  24,  61,  31,  37,  24,  61,  31,  37,  24,  61],
        [ 20,  24,  16,  20,  20,  24,  16,  20,  20,  24,  16,  20],
        [ 56,  61,  20, 986,  56,  61,  20, 986,  56,  61,  20, 986],
        [ 26,  31,  20,  56,  26,  31,  20,  56,  26,  31,  20,  56],
        [ 31,  37,  24,  61,  31,  37,  24,  61,  31,  37,  24,  61],
        [ 20,  24,  16,  20,  20,  24,  16,  20,  20,  24,  16,  20],
        [ 56,  61,  20, 986,  56,  61,  20, 986,  56,  61,  20, 986],
        [ 26,  31,  20,  56,  26,  31,  20,  56,  26,  31,  20,  56],
        [ 31,  37,  24,  61,  31,  37,  24,  61,  31,  37,  24,  61],
        [ 20,  24,  16,  20,  20,  24,  16,  20,  20,  24,  16,  20],
        [ 56,  61,  20, 986,  56,  61,  20, 986,  56,  61,  20, 986]])
tensor([[ 26,  31,  20,  56],
        [ 31,  37,  24,  61],
        [ 20,  24,  16,  20],
        [ 56,  61,  20, 986]])


tensor([[  6,   5,  30],
        [  6,   5,  41],
        [  5,   5,  21],
        [966,   5,  30]])

In [74]:
# tensor to np
t = torch.ones(5)
print(f"t: {t}")
n= t.numpy()
n

t: tensor([1., 1., 1., 1., 1.])


array([1., 1., 1., 1., 1.], dtype=float32)

In [75]:
# they share the same memory sooo
t.add_(3.14)
n

array([4.1400003, 4.1400003, 4.1400003, 4.1400003, 4.1400003],
      dtype=float32)

In [76]:
n = np.ones(5)
t= torch.from_numpy(n)
t

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [77]:
# works both ways
np.add(n,3.17,out=n)
print(f"t: {t}")
print(f"n: {n}")


t: tensor([4.1700, 4.1700, 4.1700, 4.1700, 4.1700], dtype=torch.float64)
n: [4.17 4.17 4.17 4.17 4.17]
