In [40]:
import torch
import numpy
import torchvision
# using a range of numbers torch.arange(start,end,step)
z_to_ten = torch.arange(start=0,end=10,step=1).reshape(2,5)
z_to_ten


tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [41]:
# using like
ten_zeros = torch.zeros_like(input=z_to_ten)
ten_zeros

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])

In [42]:
float_tensor = torch.tensor([3,6,9],dtype=torch.float32, device = None,requires_grad=False)
float_tensor.shape,float_tensor.dtype,float_tensor.device,float_tensor

(torch.Size([3]), torch.float32, device(type='cpu'), tensor([3., 6., 9.]))

In [43]:
float_16_t1 = torch.tensor([3.,6.,9.],dtype=torch.float16)
rand_t1 = torch.rand(3,4,2)
print(rand_t1)
print(f"Shape: {rand_t1.shape}")
print(f"Data Type: {rand_t1.dtype}")
print(f"Device: {rand_t1.device}")
# Remember for errors what shape, what datatype, where stored (cpu vs gpu)


tensor([[[0.5472, 0.0062],
         [0.9516, 0.0753],
         [0.8860, 0.5832],
         [0.3376, 0.8090]],

        [[0.5779, 0.9040],
         [0.5547, 0.3423],
         [0.6343, 0.3644],
         [0.7104, 0.9464]],

        [[0.7890, 0.2814],
         [0.7886, 0.5895],
         [0.7539, 0.1952],
         [0.0050, 0.3068]]])
Shape: torch.Size([3, 4, 2])
Data Type: torch.float32
Device: cpu


In [44]:
tensor_ops = torch.ones(2,3,4)
print(tensor_ops)
tensor_ops = tensor_ops *10
print(tensor_ops)
tensor_ops = tensor_ops - torch.multiply(tensor_ops,2)
print(tensor_ops)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor([[[10., 10., 10., 10.],
         [10., 10., 10., 10.],
         [10., 10., 10., 10.]],

        [[10., 10., 10., 10.],
         [10., 10., 10., 10.],
         [10., 10., 10., 10.]]])
tensor([[[-10., -10., -10., -10.],
         [-10., -10., -10., -10.],
         [-10., -10., -10., -10.]],

        [[-10., -10., -10., -10.],
         [-10., -10., -10., -10.],
         [-10., -10., -10., -10.]]])


In [45]:
# Matrix Multiplication (finally)
# inner dimensions must match
t3 = torch.ones(2,4,4)
t3=t3+3
print(torch.matmul(tensor_ops,t3))
t4 = torch.kron(tensor_ops,t3)
print(t4.shape)

tensor([[[-160., -160., -160., -160.],
         [-160., -160., -160., -160.],
         [-160., -160., -160., -160.]],

        [[-160., -160., -160., -160.],
         [-160., -160., -160., -160.],
         [-160., -160., -160., -160.]]])
torch.Size([4, 12, 16])


In [46]:
torch.manual_seed(42)
linear = torch.nn.Linear(in_features=3,out_features=7)
x= torch.tensor([[1,2],[3,4],[5,6]],dtype=torch.float32)
y= torch.tensor([[7,8],[9,10],[11,12]],dtype=torch.float32)

output = linear(x.T)
print(f"Input shape: {x.shape}")
print(f"Output: {output}\nOutput shape: {output.shape}")



Input shape: torch.Size([3, 2])
Output: tensor([[ 1.1350,  0.4989,  3.6639,  1.1665,  1.7869,  1.5174, -1.5052],
        [ 1.9204,  1.0193,  4.2309,  1.3528,  2.5701,  1.9662, -1.8936]],
       grad_fn=<AddmmBackward0>)
Output shape: torch.Size([2, 7])


In [47]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [48]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [49]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

In [50]:
print(f"Index of max: {x.argmax()}")
print(f"Index of min: {x.argmin()}")


Index of max: 9
Index of min: 0


In [51]:
x = torch.arange(1.,8.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [52]:
x_reshaped = x.reshape(1,7)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [ ]:
z = x.view(1,7)
z[0][1]=10000
x

tensor([1.0000e+00, 1.0000e+04, 3.0000e+00, 4.0000e+00, 5.0000e+00, 6.0000e+00,
        7.0000e+00])

In [57]:
torch.backends.mps.is_available() 
# Set device type
device = "mps" if torch.backends.mps.is_available() else "cpu"

# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='mps:0')