In [4]:
import torch
import numpy
import torchvision
# using a range of numbers torch.arange(start,end,step)
z_to_ten = torch.arange(start=0,end=10,step=1).reshape(2,5)
z_to_ten


tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [3]:
# using like
ten_zeros = torch.zeros_like(input=z_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
float_tensor = torch.tensor([3,6,9],dtype=torch.float32, device = None,requires_grad=False)
float_tensor.shape,float_tensor.dtype,float_tensor.device,float_tensor

(torch.Size([3]), torch.float32, device(type='cpu'), tensor([3., 6., 9.]))

In [ ]:
float_16_t1 = torch.tensor([3.,6.,9.],dtype=torch.float16)
rand_t1 = torch.rand(3,4,2)
print(rand_t1)
print(f"Shape: {rand_t1.shape}")
print(f"Data Type: {rand_t1.dtype}")
print(f"Device: {rand_t1.device}")
# Remember for errors what shape, what datatype, where stored (cpu vs gpu)


tensor([[[0.4965, 0.6134],
         [0.6842, 0.9256],
         [0.7924, 0.7255],
         [0.0148, 0.8100]],

        [[0.6791, 0.5960],
         [0.5823, 0.9963],
         [0.2244, 0.5661],
         [0.4820, 0.5323]],

        [[0.5948, 0.6877],
         [0.7482, 0.1703],
         [0.8478, 0.7446],
         [0.3026, 0.9472]]])
Shape: torch.Size([3, 4, 2])
Data Type: torch.float32
Device: cpu
